services:
  backend:
    image: django-tp1:0.1
    build: 
      context: ./config/django-image
    volumes:
      - ./src/django:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      red:

networks:
  red: